### ISSUE TITLE
Installation instructions on Windows are not clear in README.md

### ISSUE THREAD

**Issue by casella** [OpenModelica/OMSens#11]
@adeas31, the instructions in [https://github.com/OpenModelica/OMSens/blob/master/README.md](https://github.com/OpenModelica/OMSens/blob/master/README.md) explain how to build OMSens in Windows, but not how to install it. I guess you need to run `python setup.py install` also on Windows. Can you please make that clear?

(cc: @GianniFerretti)

**Comment by adeas31** [comment]
In general you don't need to do anything on Windows as everything is installed automatically. The instructions are correct and are there just in case you really want to build OMSens yourself. The build process handles everything so no need to install.

**Comment by GianniFerretti** [comment]
Hello, I installed python:

C:\Users\jackj>where python.exe
C:\Users\jackj\AppData\Local\Microsoft\WindowsApps\python.exe

but when I tried to set the Python executable path I got this:

![image](https://user-images.githubusercontent.com/17689020/106173078-d49bd000-6193-11eb-89f1-4fee23606e04.png)

**Comment by GianniFerretti** [comment]
I installed again python obtaining

C:\Users\jackj>where python
C:\Users\jackj\AppData\Local\Programs\Python\Python39\python.exe
C:\Users\jackj\AppData\Local\Microsoft\WindowsApps\python.exe

Trying with this path

C:\Users\jackj\AppData\Local\Programs\Python\Python39\python.exe

I got

![image](https://user-images.githubusercontent.com/17689020/106177341-ad93cd00-6198-11eb-9cd2-0446f6971ceb.png)

**Comment by GianniFerretti** [comment]
It seemes that libraries pandas and matlib were missing, however, after installing them I got this:

![image](https://user-images.githubusercontent.com/17689020/106253340-a3fd7a00-6217-11eb-8fa2-cf4f7beb9545.png)

**Comment by adeas31** [comment]
@GianniFerretti you need to use the `python` installed together with OpenModelica as it has all the dependent libraries like Pandas, matplotlib etc. installed.

So don't change the python path and leave it as `python`.

**Comment by GianniFerretti** [comment]
I tried to set this path:

C:\Program Files\OpenModelica1.16.2-64bit\tools\msys\mingw64\bin\python.exe

![image](https://user-images.githubusercontent.com/17689020/106268756-d0bb8c80-622b-11eb-8f4b-591922322686.png)

but I got

![image](https://user-images.githubusercontent.com/17689020/106268810-e6c94d00-622b-11eb-9936-c2d11cfb7e55.png)

**Comment by GianniFerretti** [comment]
Note that here

https://www.openmodelica.org/doc/OpenModelicaUsersGuide/latest/parametersensitivity.html

it is specified this

![image](https://user-images.githubusercontent.com/17689020/106269063-46bff380-622c-11eb-82a6-c758339b851c.png)

**Comment by adeas31** [comment]
Ahh I see you are using 1.16.2. Unfortunately the latest changes for Windows are not part of this release. Is it possible for you to use the latest nightly build?

**Comment by GianniFerretti** [comment]
Ok, it worked! Thank you!

**Comment by casella** [comment]
> @GianniFerretti you need to use the `python` installed together with OpenModelica as it has all the dependent libraries like Pandas, matplotlib etc. installed.

@adease31 this is a key piece of information which is not at all clear from the installation instruction. Could you please add it to the README file?

Also, if one already has other Python installations, can it coexist with the one installed by OpenModelica?

**Comment by adeas31** [comment]
> > @GianniFerretti you need to use the `python` installed together with OpenModelica as it has all the dependent libraries like Pandas, matplotlib etc. installed.
> 
> @adeas31 this is a key piece of information which is not at all clear from the installation instruction. Could you please add it to the README file?

The README already says "OMSens is installed automatically with OpenModelica on Windows.". I am not sure what more could be done. I mean the Windows user need to do nothing except to just install OpenModelica for OMSens to work. I think the confusion described in this issue came because in previous versions one need to install a special version of python and its dependencies.

> 
> Also, if one already has other Python installations, can it coexist with the one installed by OpenModelica?
Yes! but if one want to use his/her own python installation then one need to install python dependencies.

**Comment by GianniFerretti** [comment]
Maybe it is sufficient to modify this picture:

![image](https://user-images.githubusercontent.com/17689020/106288323-2e5dd200-6248-11eb-9a11-8cf0cfdbcffe.png)

It seems that you nedd to explicitly install python.

**Comment by GianniFerretti** [comment]
Good afternoon,

I tried OMSens with a simple cascade of two first order systems:

![image](https://user-images.githubusercontent.com/17689020/107151963-b8531c80-6965-11eb-8e88-1bc88209822e.png)

I didn't work:

![image](https://user-images.githubusercontent.com/17689020/107152060-2c8dc000-6966-11eb-8080-07936d17c38f.png)

I would also suggest to set the analysis results destination folder in the same directory of the model to be analyzed.

It is not possible to distinguish the state variables:

![image](https://user-images.githubusercontent.com/17689020/107152147-87271c00-6966-11eb-884a-43cafc9702df.png)

It is not possible to distinguish the parameters of the blocks:

![image](https://user-images.githubusercontent.com/17689020/107152178-b473ca00-6966-11eb-8d8b-256d5e25516b.png)

I would also suggest to select the parameters to be considered for the analysis through an annotation.

Best Regards

Gianni

**Comment by casella** [comment]
@GianniFerretti please open another ticket on this topic, this was about installation instructions and was closed one week ago. Thanks!
