### ISSUE TITLE
OMSens and aggregate models

### ISSUE THREAD

**Issue by GianniFerretti** [OpenModelica/OMSens#13]
Good afternoon,

I tried OMSens with a simple cascade of two first order systems:

image
![image](https://user-images.githubusercontent.com/17689020/107156281-bdbc6100-697d-11eb-8c58-2be936a9a5d6.png)

It didn't work:

![image](https://user-images.githubusercontent.com/17689020/107156290-ca40b980-697d-11eb-89f2-8e1155843325.png)

I would also suggest to set the analysis results destination folder in the same directory of the model to be analyzed.

It is not possible to distinguish the state variables:

image
![image](https://user-images.githubusercontent.com/17689020/107156294-d462b800-697d-11eb-80b4-45b67540b333.png)

It is not possible to distinguish the parameters of the blocks:

image
![image](https://user-images.githubusercontent.com/17689020/107156299-dcbaf300-697d-11eb-9802-aea169886263.png)

I would also suggest to select the parameters to be considered for the analysis through an annotation.

Best Regards

Gianni

**Comment by casella** [comment]
@adrpo wrote me somewhere (I can't find it now) that he probably has a clue about the error. Can @adrpo or @adeas31 take care of that?

The tool seems quite powerful, but if you can't use libraries and you can only use self-contained models, its usability is very severely restricted.

Thanks!

**Comment by adeas31** [comment]
I remember @JKRT did some work on it. Basically his idea was to write a sort of wrapper model and propagate variables to it so OMSens can use them.

**Comment by casella** [comment]
@JKRT, maybe we can discuss this at the next devmeeting on Monday? This should be clarified for end users.

**Comment by Vivek106singh** [comment]
I tried making a wrapper model but still getting same error.
Please provide some small example

**Comment by casella** [comment]
Thanks @adrpo, this is highly appreciated 😃

**Comment by casella** [comment]
@adrpo can you please port this to maintenance/v1.23, so we also get it in the 1.23.0 release? Thanks!
