### ISSUE TITLE
On Linux: OMSens plugin not found

### ISSUE THREAD

**Issue by GianniFerretti** [OpenModelica/OMSens#14]
Installed OpenModelica from Nightly Build Ubuntu repository.
When running OMSens I got the error in the subject. 
Running pip3 OMSens install I got "requirement already satisfied"
@casella

**Comment by casella** [comment]
@adeas31, @adrpo, my colleague @GianniFerretti is trying to use OMSens together with other colleagues dealing with bioreactors. The application is very interesting, unfortunately they are having several issues getting the whole thing up and running. They make good beta testers for OMSens, can you please help them?

Thanks!

**Comment by adrpo** [comment]
I have no idea if this works on Linux as you also need OMSense_Qt  (the actual Qt plugin for OMEdit) which I don't think we build or Linux at the moment.
@adeas31 any comments?

**Comment by casella** [comment]
I'm confused. I thought everything we did ran on Windows and Linux alike. Isn't that the case?

**Comment by adeas31** [comment]
It seems from the error message that OMSens_Qt is not compiled but it should be as its there in the `makefile.in` https://github.com/OpenModelica/OpenModelica/blob/master/Makefile.in#L66

I don't know how the Linux nightly builds are done. @sjoelund

**Comment by adeas31** [comment]
> I'm confused. I thought everything we did ran on Windows and Linux alike. Isn't that the case?

Kind of yes but Linux is special. You need to copy the binaries to the appropriate directories. It might be that OMSens_Qt is compiled but not copied properly.

**Comment by casella** [comment]
I hope @sjoelund can sort this out. Thanks @GianniFerretti for reporting!

**Comment by sjoelund** [comment]
It's not in https://github.com/OpenModelica/OpenModelicaBuildScripts/blob/master/debian/omedit.install and there is no OMSens package, so I guess that's why it's not installed :)

**Comment by adrpo** [comment]
I need to learn how to make a new package like omens_qt.deb and that will take a while.
If we build OMSens_Qt by default (I'm unsure if we do this for all platforms) we could just install the build/bin/plugins directory or how is called when installing OMEdit. I will start with this and then we'll split the omsense_qt package when I learn how to do it.

**Comment by casella** [comment]
In the meantime, can they fix the problem by installing some extra package manually?

**Comment by sjoelund** [comment]
@adrpo you only need to change the control file and add the corresponding .install file and a new package is generated

**Comment by adrpo** [comment]
What we need to install is this: debian/tmp/usr/lib/*/omc/libomsenseplugin.so where * is $host_short. Do we need a new package for one file?

**Comment by adrpo** [comment]
I guess for Fedora RPMs they copy everything in build/* so we don't need to care about this, is already available.

**Comment by adeas31** [comment]
We also need to update OMEdit accordingly
https://github.com/OpenModelica/OpenModelica/blob/master/OMEdit/OMEditLIB/MainWindow.cpp#L2698

**Comment by adrpo** [comment]
@adeas31 we will copy it to the usual place so OMEdit should not need any update.
I will try to make a new deb package, see how far I get.

**Comment by adrpo** [comment]
Blind try :)
https://github.com/OpenModelica/OpenModelicaBuildScripts/pull/12

**Comment by adrpo** [comment]
Seems we generate the libomsensplugin package now:
https://build.openmodelica.org/apt/dists/focal/nightly/binary-amd64/Packages
