### ISSUE TITLE
Other issues

### ISSUE THREAD

**Issue by GianniFerretti** [OpenModelica/OMSens#15]
We had to manually copy the OMSens folder, this should be included in the .deb.
Then OMSens was run form the GUI but the process crashed.
Running the command from a terminal windows the process ended correctly.
Trying to load the correctly generated result file with the Load button, the screen to view the results does not appear.
@casella

**Comment by adrpo** [comment]
@adeas31 do we install OMSens via pip, or how should be the procedure on LInux?
@GianniFerretti is the #14 solved now?

**Comment by adeas31** [comment]
No, there is pip for OMSens, one need to manually copy the OMSens folder and then run the setup.py

@GianniFerretti does the setup.py finished correctly?
