### ISSUE TITLE
OMSens problems: summary

### ISSUE THREAD

**Issue by GianniFerretti** [OpenModelica/OMSens#17]
By installing the libomsensplugin package, from the nightly build repository, these 3 problems arise:

1) The OMSens folder which contains the 3 python scripts

individual_sens_calculator.py
multiparam_sweep.py
vectorial_analysis.py

underlying "Parameter Sensitivities with OpenModelica" is missing.
There appears to be no package in the nightly build repository that provides this folder.
By recompiling the sources, and copying the OMSens folder from the sources, you can work around this problem.
It would be better to prepare a package for OMSens as well.

2) When you run from the OpenModelica GUI one of the 3 modules for "Parameter Sensitivities with OpenModelica" an error message appears containing the command line being executed, and the message
"The process has crashed".
If the command is run from the shell, the execution is successful.

3) Trying to load the results of "Parameter Sensitivities with OpenModelica" with the button "LOAD", the result display screen does not appear.

So presently it is not possible to use OMSens on Linux.

@casella

**Comment by GianniFerretti** [comment]
In the source code downloaded from GitHub for OMSens_Qt, for the OMSensDialog.cpp file in the runProcessAndShowProgress method:

271  // Start process
272  pythonScriptProcess.start(command);
273  if (pythonScriptProcess.state() == QProcess::Running) {
274   // Show dialog with progress
275    dialog->exec();
276  } else {
277   dialog->close();
278  }
279  // Wait for the process to finish in the case that we cancel the process and it doesn't have time to finish correctly
280 pythonScriptProcess.waitForFinished(3000);

- After calling pythonScriptProcess.start (command) on not very fast PCs, the process status is QProcess :: Starting and therefore the command execution status progress window is not displayed.
- The pythonScriptProcess.waitForFinished (3000) call on not very fast PCs has a too short timeout (from documentation the default is 30000)

So the code was modified in 

271  // Start process
272  pythonScriptProcess.start(command);
273  if (pythonScriptProcess.state() >= QProcess::Starting) {
274   // Show dialog with progress
275    dialog->exec();
276  } else {
277   dialog->close();
278  }
279  // Wait for the process to finish in the case that we cancel the process and it doesn't have time to finish correctly
280 pythonScriptProcess.waitForFinished(30000);

**Comment by casella** [comment]
@GianniFerretti do we need to change something in that source code for other users?
