### ISSUE TITLE
Fix "invalid escape sequence" in OMSens.

### ISSUE THREAD

**Issue by IvanLloro** [OpenModelica/OMSens#32]
Fix included in: https://github.com/OpenModelica/OpenModelica/issues/12757

**Comment by adeas31** [comment]
Please make PR from the patch.

**Comment by IvanLloro** [comment]
It is literally adding 3 letters in total in just two files. It will take much more time for me to create a PR than for you to just manually add them to your code base.

**Comment by IvanLloro** [comment]
PR submitted.

**Comment by IvanLloro** [comment]
Fixed in merged PR https://github.com/OpenModelica/OMSens/pull/33
