### ISSUE TITLE
Endless "running python script"

### ISSUE THREAD

**Issue by amirj1984** [OpenModelica/OMSens#4]
Hi, 
I have run "individual parameter-based sensitivity analysis" on several OM's built-in examples and on my own model, but unfortunately the python script running does not end. Would you please advise?

**Comment by JKRT** [comment]
Hi are you running it from OMEdit? 

There is currently an issue that OMEdit does not track the process properly, e.g if the script fails it will just keep running

**Comment by amirj1984** [comment]
Thanks @JKRT for your answer. 
Yes, I run it through OMEdit. Do you think it works in Dymola?

**Comment by JKRT** [comment]
> 
> 
> Thanks @JKRT for your answer.
> Yes, I run it through OMEdit. Do you think it works in Dymola?

Ah via the GUI? If that is the case it is an active ticket on: 

https://trac.openmodelica.org/OpenModelica/ticket/5819

I thought I had created a ticket for this other issue. It is in part related there need to be more interactivity between OMSens and OMEdit
